### ISSUE TITLE
No default export warnings

### ISSUE THREAD

**Issue by chanlito** [antfu/vue2-script-setup-transform#12]
![image](https://user-images.githubusercontent.com/15667259/130394642-656b682d-b918-4875-aa7f-b159fc39486f.png)

This is reported by components using <script setup>

**Comment by chanlito** [comment]
Changed from 
`<script lang="ts" setup>` 
to 
`<script setup lang="ts">` resolves this warning.

**Comment by wobsoriano** [comment]
Still getting this with `<script setup lang="ts">`

![Screen Shot 2021-08-24 at 1 48 14 AM](https://user-images.githubusercontent.com/13049130/130493308-79792079-2567-4d70-a82d-83194a09c406.png)

**Comment by antfu** [comment]
@wobsoriano https://github.com/antfu/vue2-script-setup-transform/commit/f052591ce54f716dcc143465027e188b77fbcbc7

Please don't reply in a closed issue next time, feel free to open a new one.
