### ISSUE TITLE
lack of macro-API (defineProps/ defineEmits/ withDefaults/ defineExpose) global type

### ISSUE THREAD

**Issue by ervinewell** [antfu/vue2-script-setup-transform#13]
![image](https://user-images.githubusercontent.com/11768033/130395070-1db2ba95-4897-41ab-ab55-919834987ae9.png)

**Comment by antfu** [comment]
Try this https://github.com/antfu/vue2-script-setup-transform/blob/main/README.md#global-types

**Comment by ervinewell** [comment]
> Try this https://github.com/antfu/vue2-script-setup-transform/blob/main/README.md#global-types

Tried.Including @vue/runtime-dom, @vue/runtime-core is neccessary too
