### ISSUE TITLE
Vue CLI still report noUnusedLocals error

### ISSUE THREAD

**Issue by chanlito** [antfu/vue2-script-setup-transform#14]
adding `"noUnusedLocals": true` to `tsconfig.json`

and vue-cli still report the following error

![image](https://user-images.githubusercontent.com/15667259/130396425-95718293-47f8-4900-ab24-5773ca221db0.png)

 IDE is fine tho

**Comment by wobsoriano** [comment]
> adding `"noUnusedLocals": true` to `tsconfig.json`
> 
> and vue-cli still report the following error
> 
> ![image](https://user-images.githubusercontent.com/15667259/130396425-95718293-47f8-4900-ab24-5773ca221db0.png)
> 
> IDE is fine tho

happening with nuxt too. But vs code is fine

**Comment by antfu** [comment]
The current workaround might be disable `noUnusedLocals` for build tools.

/cc @johnsoncodehk is there a way to explicit install volar's plugin in `tsconfig.json` or any integrations of `vue-tsc` with build tools like Vue CLI and Nuxt?

**Comment by johnsoncodehk** [comment]
I'm not familiar with build tools integration, but I think just need to [disable vue-cli's type-check](https://github.com/vuejs/vue-cli/issues/3157#issuecomment-629610739), and run `vue-tsc --noEmit && vue-cli-service build` for replacement.

**Comment by wobsoriano** [comment]
I think it's related to this? https://eslint.vuejs.org/rules/script-setup-uses-vars.html

`Definition for rule 'vue/script-setup-uses-vars' was not found.eslint(vue/script-setup-uses-vars)`
