### ISSUE TITLE
How to access `root`

### ISSUE THREAD

**Issue by Shinigami92** [antfu/vue2-script-setup-transform#2]
If possible: please provide example in README.md 
Otherwise: how can we support it?

**Comment by antfu** [comment]
What do you mean root?

**Comment by Shinigami92** [comment]
setup(_, { root }) ...

**Comment by antfu** [comment]
It's not available in Vue 3, as an workaround you might want to use

```ts
const root = getCurrentInstance().root
```

**Comment by Shinigami92** [comment]
> If possible: please provide example in README.md

Should I create a PR for that? Or do you like to add it just quickly?

And thx :slightly_smiling_face: I may try this out today

**Comment by antfu** [comment]
I don't really think it's worth mentioning, as I think it's an advanced use case (which is also out-of-scope of this project)

**Comment by Shinigami92** [comment]
Okay, let's see how often this question will rise :smile:
