### ISSUE TITLE
Maybe a performance improvement

### ISSUE THREAD

**Issue by Shinigami92** [antfu/vue2-script-setup-transform#4]
Looking through the code, I found these both lines:

https://github.com/antfu/vue2-script-setup-transform/blob/1b765dbc6950ae2cfc1f4e5ee9eeb0934a2517a3/src/transformScriptSetup.ts#L34-L35

I think we can rewrite them to only loop once through everything, potentially resulting in a little performance boost :thinking: 

```ts
const imports = []
const nodes = []

scriptSetupAst.program.body.forEach(n => {
  if (n.type === 'ImportDeclaration') {
    imports.push(n)
  } else {
    nodes.push(n)
  }
})
```

**Comment by antfu** [comment]
👀 I don't think it will be much difference giving it just a linear complexity and we will not expecting to see ppl have thousands of top-level statements in SFC anyway. I am fine for a PR if you want to.

**Comment by Shinigami92** [comment]
Will keep it in mind and will or will not do a PR, based on the results when I tried the plugin with out project
