### ISSUE TITLE
Nuxt + TS no unused vars

### ISSUE THREAD

**Issue by mirabledictu** [antfu/vue2-script-setup-transform#6]
Hello, how would someone deal with unused vars?

![Screen Shot 2021-08-21 at 7 29 43 PM](https://user-images.githubusercontent.com/86201195/130320346-c816f92d-4be5-4fec-b771-f6e47be9e682.png)

```javascript
  buildModules: [
    '@nuxt/typescript-build',
    '@nuxtjs/vuetify',
    '@nuxtjs/composition-api/module',
    'nuxt-typed-vuex',
    'vue2-script-setup-transform/nuxt',
  ],
```

Already restarted vs code and I'm using volar extension

tsconfig.json is same as the [example](https://github.com/antfu/vue2-script-setup-transform/blob/main/examples/nuxt/tsconfig.json)

**Comment by antfu** [comment]
See https://github.com/antfu/vue2-script-setup-transform#ide
